/*
 * File: app/view/UsersForm.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LiVEzerMedecine.view.UsersForm', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.selection.RowModel'
    ],

    autoShow: true,
    height: 399,
    width: 481,
    layout: {
        type: 'fit'
    },
    title: 'Users',
    maximizable: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    height: 311,
                    width: 674,
                    autoScroll: true,
                    bodyBorder: false,
                    header: false,
                    title: 'User List',
                    titleAlign: 'center',
                    columnLines: false,
                    store: 'UserList',
                    selModel: Ext.create('Ext.selection.RowModel', {
                        mode: 'MULTI'
                    }),
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            defaultWidth: 150,
                            dataIndex: 'firstName',
                            hideable: false,
                            text: 'First Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'lastName',
                            hideable: false,
                            text: 'Last Name'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 150,
                            dataIndex: 'email',
                            text: 'Email'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    enableOverflow: true,
                    displayInfo: true,
                    store: 'UserList'
                }
            ]
        });

        me.callParent(arguments);
    }

});